name: jexcel_dart
description: A Dart interface for jexcel.
# version: 1.0.0
# homepage: https://www.example.com
# author: Tony Humbert <tony.humberts@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  js: '>=0.6.1+1 <1.0.0'

dev_dependencies:
  build_runner: '>=1.5.0 <2.0.0'
  build_web_compilers: '>=1.2.0 <3.0.0'
  pedantic: ^1.7.0
  test: ^1.6.0
